/** @type {import('@remix-run/dev').AppConfig} */
export default {
  ignoredRouteFiles: ["**/.*"],
  appDirectory: "app",
  assetsBuildDirectory: "public/build",
  publicPath: "/build/",
  serverBuildPath: "build/index.js",
  serverModuleFormat: "esm",
  //serverDependenciesToBundle:
  //[
  //"@remix-run/express/*",
  //"@remix-run/node/*",
  //"@remix-run/react/*",
  //"chokidar/*",
  //"compression/*",
  //"cross-env/*",
  //"express/*",
  //"isbot/*",
  //"morgan/*",
  //"source-map-support/*",
  //"@remix-run/dev/*",
  //"@remix-run/eslint-config/*",
  //"@types/compression/*",
  //"@types/express/*",
  //"@types/morgan/*",
  //"@types/react/*",
  //"@types/react-dom/*",
  //"@types/source-map-support/*",
  //"eslint/*",
  //"react/*",
  //"react-dom/*",
  //"typescript/*",
  //],

  future: {
    v2_dev: true,
    v2_errorBoundary: true,
    v2_headers: true,
    v2_meta: true,
    v2_normalizeFormMethod: true,
    v2_routeConvention: true,
  },
};
